terror/mcgill.courses

- crates/db/Cargo.toml
- crates/db/src/db.rs
- crates/db/src/lib.rs
- src/error.rs
- src/loader.rs
- src/main.rs
- src/server.rs
- src/state.rs
- src/vsb_client.rs
GET /courses => Fetches all courses from the database
> Add courses route

- client/src/components/ProfileDropdown.tsx
=> Remove the ring
=> Tweak the hover colour to remain consistent with the search bar
> Tweak profile icon styling

- Cargo.lock
- crates/db/Cargo.toml
- crates/db/src/db.rs
- crates/db/src/lib.rs
- crates/model/Cargo.toml
- crates/model/src/lib.rs
- crates/model/src/review.rs
- src/main.rs
- src/reviews.rs
- src/server.rs
```
type Review = {
content: string;
courseId: string;
instructor: string;
rating: number;
timestamp: Date;
userId: string;
}
```
> Extend review model

- client/src/components/CourseSearchBar.tsx
> Cooler search

- client/src/components/CourseSearchBar.tsx
- client/src/components/Navbar.tsx
- client/src/pages/Home.tsx
The search bar is centered and the navigation buttons are now on the right of the nav bar.
> Added search bar in nav bar for non-home pages 

- client/src/App.tsx
- client/src/pages/About.tsx
- package-lock.json
- package.json
Really simple prototype of an about page. This will be a placeholder for now, and we can adjust before deployment.
> About page

- .prettierrc
- client/src/components/AddReviewForm.tsx
- client/src/components/Alert.tsx
- client/src/components/Autocomplete.tsx
- client/src/components/CourseCard.tsx
- client/src/components/CourseInfo.tsx
- client/src/components/CourseRequirements.tsx
- client/src/components/CourseReview.tsx
- client/src/components/CourseReviewPrompt.tsx
- client/src/components/CourseSearchBar.tsx
- client/src/components/CourseTerms.tsx
- client/src/components/DeleteButton.tsx
- client/src/components/EditReviewForm.tsx
- client/src/components/NavItem.tsx
- client/src/components/Navbar.tsx
- client/src/components/ReviewForm.tsx
- client/src/components/Spinner.tsx
- client/src/pages/About.tsx
- client/src/pages/CoursePage.tsx
- client/src/pages/Explore.tsx
- client/src/pages/Home.tsx
- package-lock.json
- package.json
docs: https://github.com/tailwindlabs/prettier-plugin-tailwindcss
Signed-off-by: Joey Yu <joey@itsjoeoui.com>
> Properly format tailwind class

- client/src/components/CourseInfo.tsx
- client/src/components/RatingPieChart.tsx
- client/src/components/StarRating.tsx
- client/src/pages/CoursePage.tsx
- package-lock.json
- package.json
Added a pie chart on course pages to display the average rating.
It is also responsive it terms of its parent, the size adjusts as the screen width adjust, and becomes centred as the screen gets to about phone-size.
> Course Rating Display

- client/src/components/CourseSearchBar.tsx
- crates/extractor/mocks/course_page_with_amp.html
- crates/extractor/src/course_listing_ext.rs
- crates/extractor/src/course_page_ext.rs
- crates/extractor/src/lib.rs
Changed `&amp;` parsing to extractor
added a test for a course page with `&`
> Parse &amp; on extractor instead of frontend 

- client/index.html
- Fix search result z-index on explore page (#168)
- Add overflow-auto to layout component (#169)
- Add FAQ to about page (#170)
- change website title
> change website title to mcgill.courses

- client/src/components/Footer.tsx
- client/src/components/Layout.tsx
- client/src/components/NavItem.tsx
- client/src/components/Navbar.tsx
- client/src/components/SideNav.tsx
- Move nav items to footer
- lint
> Move nav bar items to a footer

- client/src/components/CourseTerms.tsx
I made it like this because space feels a bit tight, but I can implement it like a tooltip if you prefer 
https://user-images.githubusercontent.com/112342947/236613601-3e0227a1-a67f-4f1e-95b1-da663876b06e.mov
> add hover effect for course term icons

- client/src/components/CourseRequirements.tsx
- client/src/pages/CoursePage.tsx
- pin user review first
- remove redundant code
- pin user review to first
- update course requirement ui
- add links to pre-reqs and co-reqs
> Pin user review in coursepage

- client/src/components/Alert.tsx
- client/src/components/CourseInfo.tsx
- client/src/components/CourseRequirements.tsx
- client/src/components/CourseReview.tsx
- client/src/components/CourseReviewPrompt.tsx
- client/src/components/RatingPieChart.tsx
- client/src/components/ReviewForm.tsx
- client/src/pages/CoursePage.tsx
Zoom zoom blazingly fast
- Move navbar items into a footer (#182)
- Update dependencies (#185)
- Remove unnecessary refs from db::courses (#186)
- Add tooltips for course term icons (#184)
- Add internal links to course prerequisites and corequisites (#187)
- Pin current users review in course page (#183)
- correct error message for review rating
> responsive course page

- client/src/components/CourseRequirements.tsx
> Show "This course has no x" for courses without some requirements

- client/src/components/CourseRequirements.tsx
- client/src/pages/CoursePage.tsx
https://github.com/terror/mcgill.courses/assets/112342947/98a708af-9971-4d98-a124-58866eb7c6fe
> Add show all reviews button

- client/src/components/CourseInfo.tsx
- client/src/components/CourseRequirements.tsx
- client/src/components/CourseReview.tsx
- client/src/components/SchedulesDisplay.tsx
- client/src/lib/utils.ts
- client/src/pages/CoursePage.tsx
> Sort and group course schedule information

- client/src/components/CourseTerms.tsx
- fix no terms shown when not offered in explore page course cards
- fmt
> Fix no terms being shown when not currently offered in course cards, explore page

- client/src/components/CourseReview.tsx
https://github.com/terror/mcgill.courses/assets/112342947/24d6d0df-00d5-4cd0-80e0-b8cc3f6106f9
> Added prompt for non-logged-in users when they try to like a review

- client/src/components/SchedulesDisplay.tsx
> Fixed schedule displaying invisible texts

- client/src/components/AddReviewForm.tsx
- client/src/components/DeleteButton.tsx
- client/src/components/EditReviewForm.tsx
- client/src/pages/CoursePage.tsx
> Fix stutter when closing dialogs

- client/src/pages/CoursePage.tsx
> Fix bug where review form closes upon clicking on it

- client/src/components/CourseGraph.tsx
- client/src/components/CourseInfo.tsx
- client/src/components/CourseSearchBar.tsx
- client/src/components/RatingPieChart.tsx
- client/src/lib/utils.ts
- client/src/pages/Instructor.tsx
- client/src/pages/Profile.tsx
> Add header to profile page

- client/src/components/CourseReview.tsx
> Highlight review card course on instructor page

- client/src/components/CourseReview.tsx
> Add pin icon to user review

- client/src/components/CourseInfo.tsx
- client/src/components/CourseInfoStats.tsx
> Show histogram on smaller screen

- client/src/components/Navbar.tsx
> Fix bird getting squished

- client/src/components/NotificationDropdown.tsx
> Make notification dot red

- client/src/components/ReviewFilter.tsx
> Fix absolutely positioned reset button

- client/src/components/CourseInfo.tsx
fixed histogram going outside of background
> 423 fix histogram display on specific screen sizes

- client/src/components/ExploreFilter.tsx
- client/src/components/MultiSelect.tsx
> Adjust explore filter text color to be closer to other page elements

- client/src/components/CourseReviewPrompt.tsx
- client/src/components/ProfileDropdown.tsx
- client/src/components/ReviewEmptyPrompt.tsx
- client/src/model/User.ts
- client/src/pages/CoursePage.tsx
- client/src/pages/Explore.tsx
- client/src/pages/Profile.tsx
Mainly profile page, but also mobile explore and empty states for course page.
> Miscellaneous style tweaks

- README.md
- client/src/pages/Home.tsx
It was missed, the link and hover was covering the entire row instead of just the text
> Add horizon margin to the new explore button

- client/src/components/ExploreFilter.tsx
- client/src/hooks/useExploreFilterState.ts
- client/src/main.tsx
- client/src/pages/Explore.tsx
- client/src/providers/ExploreFilterStateProvider.tsx
> Persist explore filter state until page refresh

- client/src/pages/About.tsx
- client/src/pages/PrivacyPolicy.tsx
- client/src/pages/TermsAndConditions.tsx
Thoughts on putting the Discord server instead of an admin email?
> Add Discord link to the contacts

- client/index.html
> Add a simple meta description tag

- client/index.html
- client/src/main.tsx
- client/src/pages/About.tsx
- client/src/pages/CoursePage.tsx
- client/src/pages/Explore.tsx
- client/src/pages/Instructor.tsx
- client/src/pages/PrivacyPolicy.tsx
- client/src/pages/Profile.tsx
- client/src/pages/Reviews.tsx
- client/src/pages/TermsAndConditions.tsx
- package.json
- pnpm-lock.yaml
Added seo meta tags for all pages
> Add seo meta tags for all pages

- client/src/components/SideNav.tsx
> Fix sidebar z index

- .github/workflows/ci.yaml
- client/src/components/CourseAverages.tsx
- client/src/components/CourseTerms.tsx
- client/src/components/SchedulesDisplay.tsx
- client/src/lib/utils.ts
- package.json
- pnpm-lock.yaml
Resolves #521 
https://github.com/terror/mcgill.courses/assets/47371088/7a74df6a-3f7e-42ad-89ec-351e294c63b3
Additionally:
- Added `immer` for easy nested state updates
- Fixed key errors in some other components
> Support displaying multiple instructors in course terms

- client/src/components/CourseTerms.tsx
- client/src/lib/utils.ts
> Remove click handler from course terms without instructor

- client/src/components/CourseAverages.tsx
- client/src/components/CourseTerms.tsx
> Display full list of instructors in course averages

- client/src/pages/CoursePage.tsx
> Update empty state text for course page

- client/src/components/SchedulesDisplay.tsx
- client/src/model/Schedule.ts
- crates/extractor/src/element.rs
- crates/extractor/src/lib.rs
- crates/model/src/schedule.rs
- src/loader.rs
- src/vsb_client.rs
Adds CRNs to course schedules.
Resolves #577 
Rescraped 2024-2025 courses/schedules because of this.
> Display course CRNs in schedules

- .github/workflows/ci.yaml
- client/src/components/ProfileDropdown.tsx
> Improve hover styling on profile dropdown

- .github/workflows/ci.yaml
- client/src/components/CourseReview.tsx
- client/src/pages/Reviews.tsx
- crates/db/src/db.rs
- crates/db/src/lib.rs
> Differentiate scraped reviews

- client/src/components/CourseSearchBar.tsx
- client/src/components/SearchBar.tsx
- client/src/pages/Home.tsx
like google
You can give it a try to see if you like it. This is disabled on tablets and phone
> Automatically focus the search bar on home screen for desktops

- client/src/components/CourseCard.test.tsx
- client/src/model/Course.ts
- crates/db/src/db.rs
- crates/db/test-seeds/after_update.json
- crates/db/test-seeds/before_update.json
- crates/db/test-seeds/mini.json
- crates/db/test-seeds/mix.json
- crates/db/test-seeds/search.json
- crates/db/test-seeds/update.json
- crates/extractor/src/ecalendar_extractor.rs
- crates/extractor/src/lib.rs
- crates/model/src/course.rs
- crates/model/src/course_page.rs
- src/loader.rs
Not used anywhere and we can't really get it in the new course catalog
> Remove faculty url field on course

- client/src/components/CourseInfo.tsx
> Display credits in course info

- Cargo.lock
- Cargo.toml
- client/src/lib/api.ts
- crates/db/src/db.rs
- crates/db/src/lib.rs
- crates/model/Cargo.toml
- crates/model/src/course.rs
- crates/model/src/course_filter.rs
- crates/model/src/datetime.rs
- crates/model/src/instructor.rs
- crates/model/src/lib.rs
- crates/model/src/requirements.rs
- crates/model/src/review.rs
- crates/model/src/schedule.rs
- src/courses.rs
- src/documentation.rs
- src/main.rs
- src/server.rs
> Serve public API documentation
